# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

def common_pods
  pod 'Kingfisher'
end

target 'MarvelCharactersDemo' do
  common_pods
end

target 'MarvelCharactersDemoTests' do
  common_pods
end

